/**
* $themeColor, $themeColorDarken, $textColor, $textOnThemeColor, $linkColor, $linkHoverColor, $linkOnThemeColor, $linkHoverOnThemeColor
*/

/**
* Header mobile
*/

.header-mobile .mobile-top{
background-color: #<?php echo $themeColor; ?>;
}

.header-mobile .mobile-menu > a span{
background-color: #<?php echo $textOnThemeColor; ?>;
}

.minicart-mobile .minicart-wrapper .action.showcart:before{
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* General
*/

.text-theme-color{
color: #<?php echo $themeColor; ?>;
}

.bundle-actions .action.primary:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Control owl slider
*/

.nav-style-1 .owl-theme .owl-nav [class*="owl-"]:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.nav-style-2 .owl-theme .owl-nav [class*="owl-"]:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.nav-style-3 .owl-theme .owl-nav [class*="owl-"]:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Header 1
*/

.header-1-style .install-sm a,
.header-1-style .install-sm{
color: #<?php echo $textOnThemeColor; ?>;
}

.header-1-style .install-sm a:hover{
border-bottom: 1px dotted #<?php echo $textOnThemeColor; ?>;
}

.header-1-style .header-bottom{
background-color: #<?php echo $themeColor; ?>;
}

.header-1-style .desktop-menu .navigation .level0 > .level-top{
color: #<?php echo $textOnThemeColor; ?>;
}

.header-1-style .block-right .block-content > .header.links > li > a:hover{
color: #<?php echo $linkHoverColor; ?>;
}


/**
* Home page
*/
.dot-style-1.dot-white .owl-theme .owl-dots .owl-dot.active span,
.dot-style-1.dot-white .owl-theme .owl-dots .owl-dot:hover span{
background-color: #<?php echo $themeColor; ?>;
}

.list-services .item:hover{
border-color: #<?php echo $themeColor; ?>;
}

.bottom-title .block .block-title:before{
background-color: #<?php echo $themeColor; ?>;
}


.block-news .post-read-more a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Listing
*/
#price-slider .ui-slider-range{
background-color: #<?php echo $themeColor; ?>;
}

.modes .modes-mode:hover,
.modes .modes-mode.active{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.pages .item:hover,
.pages .current{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
}

.pages .item a:hover,
.pages .current strong{
color: #<?php echo $textOnThemeColor; ?>;
}

.pages .action:hover:before{
color: #<?php echo $textOnThemeColor; ?>!important;
}

.sidebar .block .block-title{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.sidebar .block.filter .filter-options .filter-options-content ol li a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

.products-list .product-item-info .product-item-details .product-item-actions .actions-primary .tocart:hover,
.products-list .product-item-info .product-item-details .product-item-actions .actions-secondary .action:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-1-style .products-grid .product-item-info .product-item-details .product-item-actions .actions-secondary .action:hover,
.product-1-style .products-grid .product-item-info .product-item-details .product-item-actions .actions-primary .tocart:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Detail page
*/

.default-style .resp-tabs-list li.active:before{
background-color: #<?php echo $themeColor; ?>;
}

.default-style .resp-tabs-list li.active,
.default-style .resp-tabs-list li:hover{
color: #<?php echo $themeColor; ?>;
}

.fotorama__thumb-border{
border-color: #<?php echo $themeColor; ?>!important;
}

.gallery-placeholder .fotorama__thumb__arr:hover{
background-color: #<?php echo $themeColor; ?>;
border-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-info-main .product-social-links .action:hover,
.product-info-main .product-addto-links .action:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>!important;
}

.product-info-main .box-tocart .action.tocart,
.product-options-bottom .box-tocart .action.tocart{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.product-info-main .box-tocart .action.tocart:hover,
.product-options-bottom .box-tocart .action.tocart:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

/**
* Footer 1
*/

.footer-style-1 .block-footer.block-links .block-footer-content ul li a:hover{
color: #<?php echo $linkHoverColor; ?>;
}

.footer-style-1 .block-footer.block-links .block-footer-content ul li a:before{
background-color: #<?php echo $linkHoverColor; ?>;
}

.footer-style-1 .block-footer .footer-contact ul li:before{
color: #<?php echo $linkHoverColor; ?>;
}

.footer-style-1 .social-footer ul li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-1 .newsletter-footer .action-button button{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.footer-style-1 .newsletter-footer .action-button button:hover{
background-color: #<?php echo $themeColorDarken; ?>;
}

/**
* About us
*/

.about-container .our-member .image-content .member-social li a:hover,
.about-container .our-client-say .nav-style-1 .owl-theme .owl-nav [class*="owl-"]:hover,
.about-container .our-member .nav-style-1 .owl-theme .owl-nav [class*="owl-"]:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

/**
* Contact page
*/

.contact-us-info .contact-social li a:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.contact-us-info .info-contact li:before{
color: #<?php echo $themeColor; ?>;
}

/**
* Blog page
*/

.post-content.post-custom .post-description .post-info-blog .post-read-more:hover{
background-color: #<?php echo $themeColor; ?>;
color: #<?php echo $textOnThemeColor; ?>;
}

.post-content.post-custom .post-description .post-title a:hover{
color: #<?php echo $linkHoverColor; ?>;
}
