<?php
/*------------------------------------------------------------------------
# SM Filter Products - Version 1.3.0
# Copyright (c) 2016 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

use Magento\Framework\App\Action\Action;

$_productCollection = $block->getLoadedProductCollection();
$_helper            = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
            echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <?php
    $viewMode        = 'grid';
    $image           = 'category_page_list_small';
    $showDescription = false;
    $templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $showWishlist    = true;
    $showCompare     = true;
    $showCart        = true;
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos    = $block->getPositioned();
    $tag_id = $this->_tagId();
    ?>
    <div class="block block-list-products">
        <?php if (!empty($this->_getConfig('title_module'))) { ?>
            <div class="block-title">
                <strong><?php echo $this->_getConfig('title_module'); ?></strong>
            </div>
        <?php } ?>

        <div class="block-content">
            <div id="<?php echo $tag_id; ?>" class="product-type-list">

                <?php
                if ($this->_getConfig('product_source') == 'countdown_products') {
                    $dateTo = $this->_getConfig('date_to', '');
                    ?>
                    <div class="deals-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($dateTo)); ?>">
                        <div class="deals-time time-day">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                        <div class="deals-time time-hours">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                        <div class="deals-time time-mins">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                        <div class="deals-time time-secs">
                            <div class="num-time"></div>
                            <div class="title-time"></div>
                        </div>
                    </div>
                <?php } ?>

                <?php $iterator = 1; ?>
                <div class="products list items product-items filterproducts">
                    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                    <?php foreach ($_productCollection as $_product):
                        ?>
                        <div class="item product product-item">
                            <div class="product-item-info" data-container="product-grid">
                                <?php
                                $productImage = $block->getImage($_product, $image);
                                if ($pos != null) {
                                    $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                        . 'top:' . $productImage->getHeight() . 'px;"';
                                }
                                ?>

                                <?php // Product Image
                                ?>
                                <div class="image-product">
                                    <a href="<?php /* @escapeNotVerified */
                                    echo $_product->getProductUrl() ?>" class="product photo product-item-photo"
                                       tabindex="-1">
                                        <?php echo $productImage->toHtml(); ?>
                                    </a>
                                </div>

                                <div class="product details product-item-details">
                                    <?php
                                    if ((int)$this->_getConfig('display_countdown') && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) {
                                        $specialToDate = $_product->getSpecialToDate();
                                        ?>
                                        <div class="deals-countdown"
                                             data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>">
                                            <div class="deals-time time-day">
                                                <div class="num-time"></div>
                                                <div class="title-time"></div>
                                            </div>
                                            <div class="deals-time time-hours">
                                                <div class="num-time"></div>
                                                <div class="title-time"></div>
                                            </div>
                                            <div class="deals-time time-mins">
                                                <div class="num-time"></div>
                                                <div class="title-time"></div>
                                            </div>
                                            <div class="deals-time time-secs">
                                                <div class="num-time"></div>
                                                <div class="title-time"></div>
                                            </div>
                                        </div>
                                    <?php } ?>

                                    <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    ?>
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                           href="<?php /* @escapeNotVerified */
                                           echo $_product->getProductUrl() ?>">
                                            <?php /* @escapeNotVerified */
                                            echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    </strong>
                                    <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                    <?php
                                    /* @escapeNotVerified */
                                    echo $block->getProductPrice($_product) ?>
                                    <?php echo $block->getProductDetailsHtml($_product); ?>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        require([
            'jquery'
        ], function ($) {
            ;(function (el) {
                var $element = $(el);

                function _countDown(date, id) {
                    var dateNow = new Date();
                    var amount = date.getTime() - dateNow.getTime();
                    delete dateNow;
                    if (amount < 0) {
                        id.html("Now!");
                    } else {
                        var days = 0;
                        hours = 0;
                        mins = 0;
                        secs = 0;
                        out = "";
                        amount = Math.floor(amount / 1000);
                        days = Math.floor(amount / 86400);
                        amount = amount % 86400;
                        hours = Math.floor(amount / 3600);
                        amount = amount % 3600;
                        mins = Math.floor(amount / 60);
                        amount = amount % 60;
                        secs = Math.floor(amount);
                        $(".time-day .num-time", id).text(days);
                        $(".time-day .title-time", id).text(((days <= 1) ? "<?php echo __('Day') ?>" : "<?php echo __('Days') ?>"));
                        $(".time-hours .num-time", id).text(hours);
                        $(".time-hours .title-time", id).text(((hours <= 1) ? "<?php echo __('Hour') ?>" : "<?php echo __('Hours') ?>"));
                        $(".time-mins .num-time", id).text(mins);
                        $(".time-mins .title-time", id).text(((mins <= 1) ? "<?php echo __('Min') ?>" : "<?php echo __('Mins') ?>"));
                        $(".time-secs .num-time", id).text(secs);
                        $(".time-secs .title-time", id).text(((secs <= 1) ? "<?php echo __('Sec') ?>" : "<?php echo __('Secs') ?>"));
                        setTimeout(function () {
                            _countDown(date, id)
                        }, 1000);
                    }
                }

                $(".deals-countdown", $element).each(function () {
                    var timer = $(this).data('timer');
                    var data = new Date(timer);
                    _countDown(data, $(this));
                });
            })('#<?php echo $tag_id ?>');
        });
    </script>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }



        

        </script>
    <?php endif; ?>
<?php endif; ?>
