<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="display-popup" style="display:none;">
    <div id="newsletter-popup">
        <form class="form subscribe"
              novalidate
              action="<?php /* @escapeNotVerified */
              echo $block->getFormActionUrl() ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="newsletter-popup-validate-detail">
            <div class="w-newsletter">
                <div class="newsletter-info">
                    <div class="popup-news-title"><?php echo __('Newsletter sign up ') ?></div>

                    <div class="news-description"><?php echo __('Enter your email below to receive a $30 coupon, special offers, exclusive discounts and more!') ?></div>

                    <div class="form-newsletter-popup">
                        <div class="input-box">
                            <input name="email" type="email" id="newsletter-popup-input" class="input-text"
                                   onfocus="if(this.value=='<?php echo __("Your email address") ?>') this.value='';"
                                   onblur="if(this.value=='') this.value='<?php echo __("Your email address") ?>';"
                                   value="<?php echo __("Your email address") ?>"
                                   data-validate="{required:true, 'validate-email':true}"/>
                        </div>

                        <div class="action-newsletter">
                            <button class="action subscribe primary" title="<?php /* @escapeNotVerified */
                            echo __('Subscribe') ?>" type="submit">
										<span><?php /* @escapeNotVerified */
                                            echo __('Subscribe') ?></span>
                            </button>
                        </div>
                    </div>

                    <div class="subscribe-bottom">
                        <div id="uniform-dont-show-again" class="checker"><span><input id="dont-show-again"
                                                                                       type="checkbox"></span>
                        </div>
                        <label for="dont-show-again"><?php echo __('Don\'t show this popup again') ?></label>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
